### PR TITLE
SignCheck fixes

### LINKED ISSUE #3749: Using SignCheck to verify that a file is not signed
Is there a way to verify that a file isn't signed using SignCheck?

Core-Setup produces a couple of template files, `apphost.exe`/`comhost.dll`, that must not be signed, and I'm concerned that slight changes to logic might cause signing to pick it up at some point. If that happens, I want it to break the Core-Setup official build. More info about the templates: https://github.com/dotnet/core-setup/pull/7549.

If that's not possible (and I suppose it's fairly niche), would it be possible to add this feature?

@joeloff

/cc @JohnTortugo @MichaelSimons @dleeapho @vitek-karas

### PR DESCRIPTION
**Pull request by joeloff**
1. Fixes #3749 - exclusions can now include a special comment "DO-NOT-SIGN" to report signed files that should not be signed as errors
2. Better handling for file patterns/parents in exclusions
3. Special case handling for archive files (nupkg, zip) that include MSIs with external CAB files to ensure that the files are all extracted first as files cannot be extracted from the MSI if the external CAB isn't available.
4. Includes a check to verify repository signatures in NuGet packages. This is a new feature in NuGet where any package published to nuget.org is automatically signed with a repository certificate.

### CODE REVIEW

**Comment by markwilkie** [comment]
Thanks @joeloff !

@JohnTortugo is probably interested as well.

File: src/SignCheck/Microsoft.SignCheck/Verification/Exclusions.cs [hunk 1]
```diff
@@ -79,24 +108,20 @@ public bool Contains(Exclusion exclusion)
...
-            }
+        /// <summary>
+        /// Returns true if the file pattern matches the file and the exclusion comment contains DO-NOT-SIGN.
+        /// </summary>
+        /// <param name="path"></param>
+        /// <returns></returns>
+        public bool IsDoNotSign(string path, string parent, string containerPath)
+        {
+            // Get all the exclusions with DO-NOT-SIGN markers and check only against those
+            IEnumerable<Exclusion> doNotSignExclusions = _exclusions.Where(e => e.Comment.Contains("DO-NOT-SIGN"));
```
Comment (dagood) [inline src/SignCheck/Microsoft.SignCheck/Verification/Exclusions.cs]: Add `.ToArray()` to avoid multiple enumeration?

File: src/SignCheck/Microsoft.SignCheck/Verification/Exclusions.cs [hunk 2]
```diff
@@ -70,6 +70,35 @@ public bool Contains(Exclusion exclusion)
             return _exclusions.Contains(exclusion);
         }
 
+        public bool IsExcluded(string path, string parent, string containerPath, IEnumerable<Exclusion> exclusions)
+        {
+            foreach(Exclusion e in exclusions)
```
Comment (dagood) [inline src/SignCheck/Microsoft.SignCheck/Verification/Exclusions.cs]:
```suggestion
            foreach (Exclusion e in exclusions)
```

File: src/SignCheck/Microsoft.SignCheck/Verification/Exclusions.cs (hunk 1 above)
Comment (joeloff) [reply src/SignCheck/Microsoft.SignCheck/Verification/Exclusions.cs]: I've pushed a change to fix this
